on:
  pull_request:

name: CI

permissions:
  contents: read

jobs:
  check:
    name: Check and Clippy (${{ matrix.os }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runner: avrea-ubuntu-latest-4-vcpu
          - os: macos-latest
            runner: avrea-macos-26-8-vcpu
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      # Create empty worker build artifacts
      - run: mkdir -p worker/build
      - run: touch worker/build/index.js
      - run: touch worker/build/index_bg.wasm
      - run: cargo check --all
      - run: rustup component add clippy
      - run: cargo clippy

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check

  test:
    name: Test Suite (${{ matrix.os }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runner: avrea-ubuntu-latest-4-vcpu
          - os: macos-latest
            runner: avrea-macos-26-8-vcpu
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      # TODO(augustoccesar)[2026-05-04]: From 0.7.0, the worker-build version is aligned
      #   with the version of the worker crate. When bumping the worker, it needs to also
      #   bump the worker-build.
      - name: Pre-build Worker
        working-directory: worker
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install -q worker-build@0.8.7
          worker-build --release

      - name: Start Wrangler Worker
        working-directory: worker
        run: |
          cp wrangler.ci.toml wrangler.toml
          npm install -g wrangler@latest
          nohup npx wrangler@latest dev > wrangler.log 2>&1 &
          tail -f wrangler.log | while read LOGLINE
          do
            echo "${LOGLINE}"
            [[ "${LOGLINE}" == *"Ready on http://localhost:8787"* ]] && pkill -P $$ tail
          done

      - run: cd $GITHUB_WORKSPACE && cargo test --all-features -- --include-ignored

  worker-build:
    name: Worker build
    runs-on: avrea-ubuntu-latest-4-vcpu
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-targets: "false"
      # TODO(augustoccesar)[2026-02-25]: From 0.7.0, the worker-build version is aligned
      #   with the version of the worker crate. When bumping the worker, it needs to also
      #   bump the worker-build.
      - run: cargo install -q worker-build@0.8.7
      - run: worker-build --release
        working-directory: worker
